---
title: "Interactive penguins"
author: "Katie Munster"
date: "10/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages
library(tidyverse)
library(palmerpenguins)
library(plotly)
library(DT)
library(here)

# install.packages("package_name")
```

Scatterplot of penguin flipper_length_mm (x-axis) versus body_mass_g (y-axis), with points having different colors based on species

Use 'View(penguins)' to see the dataset.
```{r}
penguins_graph <- ggplot(data = penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
         geom_point(aes(color = species))



ggplotly(penguins_graph)
```

```{r}
datatable(penguins)
```

I'm going to make a column graph (using geom_bar) of counts of penguins by island, wiht fill color indicating penguin species. Then we're going to save that using 'ggsave()'.

```{r}
ggplot(data = penguins, aes(x = island)) +
  geom_bar(aes(fill = species))


ggsave(here("final_figures", "island_counts.png"))
```




